### PR TITLE
Remove insets from scroll view

### LINKED ISSUE #7: 🐞 Selection highlight overflow is drawn just above bottom viewport edge
### Description

When selecting text beyond the bottom edge (top is fine), the selection highlight is drawn just above the bottom edge.

### To Reproduce

1. Select multiple lines of text
2. Scroll up so that selection highlight exceeds the bottom edge of the text view viewport.

### Expected Behavior

Selection highlight is drawn flush with the bottom edge of the text view viewport.

### Version Information

CodeEditTextView: 0.7.0
macOS: 14.0
Xcode: 15.0

### Screenshots

image

### PR DESCRIPTION
**Pull request by danielzsh**
### Description

Before: see https://github.com/CodeEditApp/CodeEdit/issues/1700
After:

https://github.com/CodeEditApp/CodeEditTextView/assets/65467530/a6ce46fa-6576-4c23-8e72-0af64861d168

### Related Issues

* Closes https://github.com/CodeEditApp/CodeEdit/issues/1700
* Closes #7 

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code

### CODE REVIEW

**Comment by danielzsh** [comment]
Oh shoot, just realized the line numbers are now bleeding over the edge...will see what I can about that 😓

**Comment by danielzsh** [comment]
@austincondiff sorry I'm really new to Swift and am probably missing a really easy way to fix this issue; any pointers? I think the issue stems from the fact that `gutterView` is added via `addFloatingSubview`, which causes it to display over the horizontal scrollbar, but I can't figure out how to get it to display under.

**Comment by austincondiff** [comment]
It looks like the line numbers are fine. The text and selection don't come down far enough though.

@thecoolwinter any thoughts on this?

**Comment by danielzsh** [comment]
By the way, should we potentially hide the horizontal scrollbar if there's nothing to scroll horizontally/if word wrapping is turned on?

**Review by thecoolwinter — APPROVED** [review]

**Comment by austincondiff** [comment]
Oh, I see. The line numbers are overlapping the horizontal scrollbar. Two things need to happen here:
1. Line numbers should stop at the horizontal scrollbar if it is displayed.
2. If there is not horizontal overflow, horizontal scrollbar should be hidden.

**Review by FastestMolasses — APPROVED** [review]

**Pull request merged**
